name: pgai_rag_demo

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - rag_network
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.pg
    container_name: pgai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: [ "-c", "ai.ollama_host=http://ollama:11434" ]
    networks:
      - rag_network

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    container_name: pgai_vectorizer_worker
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
      OLLAMA_HOST: http://ollama:11434
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]

volumes:
  postgres_data:

networks:
  rag_network:
    driver: bridge